// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DigiProc.Models.Domain
{
    [Table("CommitteeMember")]
    public partial class CommitteeMember
    {
        [Key]
        [Column("CommitteeMemberID")]
        public int CommitteeMemberId { get; set; }
        [Column("CommitteeID")]
        public int? CommitteeId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string OtherNames { get; set; }
        [Column("PositionID")]
        public int? PositionId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string EmailAddress { get; set; }
    }
}