// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DigiProc.Models.Domain
{
    [Table("FinancialYear")]
    public partial class FinancialYear
    {
        /// <summary>
        /// primary key
        /// </summary>
        [Key]
        [Column("FinancialYrID")]
        public int FinancialYrId { get; set; }
        /// <summary>
        /// the financial year in question. limited to char(9) eg: 2022-2023
        /// </summary>
        [StringLength(9)]
        [Unicode(false)]
        public string FinancialYr { get; set; }
    }
}