// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DigiProc.Models.Domain
{
    [Table("Item")]
    public partial class Item
    {
        /// <summary>
        /// the primary key of Items
        /// </summary>
        [Key]
        [Column("ItemID")]
        public int ItemId { get; set; }
        /// <summary>
        /// the name of the item
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string ItemName { get; set; }
        /// <summary>
        /// the item code
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string ItemCode { get; set; }
        /// <summary>
        /// minimum stock level
        /// </summary>
        public int? MinStockLevel { get; set; }
        /// <summary>
        /// the description for the item
        /// </summary>
        [StringLength(200)]
        [Unicode(false)]
        public string ItemDescription { get; set; }
        [Column("SIUnitID")]
        public int? SiunitId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LastUpdatedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime? LastUpdatedDate { get; set; }
    }
}