// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DigiProc.Models.Domain
{
    [Table("LPO")]
    public partial class Lpo
    {
        [Key]
        [Column("LPOID")]
        public int Lpoid { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string RequisitionNo { get; set; }
        [Column("VAT", TypeName = "numeric(9, 2)")]
        public decimal? Vat { get; set; }
        [Column(TypeName = "date")]
        public DateTime? PurchaseOrderDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ExpectedDeliveryDate { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string ShippingAddress { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string PaymentTerm { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string OtherTermsAndConditions { get; set; }
    }
}