// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DigiProc.Models.Domain
{
    [Table("PriorityType")]
    public partial class PriorityType
    {
        /// <summary>
        /// primary key for the Priority lookup
        /// </summary>
        [Key]
        [Column("PriorityID")]
        public int PriorityId { get; set; }
        /// <summary>
        /// priority description
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string PriorityDescription { get; set; }
    }
}