// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DigiProc.Models.Domain
{
    [Table("RequisitionItem")]
    public partial class RequisitionItem
    {
        /// <summary>
        /// primary key for the table entity
        /// </summary>
        [Key]
        [Column("RequisitionItemID")]
        public int RequisitionItemId { get; set; }
        /// <summary>
        /// the ID of the requisition
        /// </summary>
        [Column("RequisitionID")]
        public int? RequisitionId { get; set; }
        /// <summary>
        /// the ID of the item
        /// </summary>
        [Column("ItemID")]
        public int? ItemId { get; set; }
        /// <summary>
        /// the quantity being requisitioned
        /// </summary>
        public int? Quantity { get; set; }
        /// <summary>
        /// the rate for the item being requisitioned
        /// </summary>
        [Column(TypeName = "numeric(9, 2)")]
        public decimal? ItemRate { get; set; }
        /// <summary>
        /// Quantity x Rate gives ITEM AMOUNT
        /// </summary>
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? ItemAmount { get; set; }
    }
}