// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DigiProc.Models.Domain
{
    [Table("RequisitionStatus")]
    public partial class RequisitionStatus
    {
        /// <summary>
        /// primary key
        /// </summary>
        [Key]
        [Column("RequisitionStatusID")]
        public int RequisitionStatusId { get; set; }
        /// <summary>
        /// the current status of a requisition
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string RequisitionStatusDesc { get; set; }
    }
}