// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DigiProc.Models.Domain
{
    [Table("Requisition")]
    public partial class Requisition
    {
        /// <summary>
        /// primary key
        /// </summary>
        [Key]
        [Column("RequisitionID")]
        public int RequisitionId { get; set; }
        /// <summary>
        /// requisition number
        /// </summary>
        [StringLength(25)]
        [Unicode(false)]
        public string RequisitionNo { get; set; }
        /// <summary>
        /// the ID of the requester
        /// </summary>
        [Column("RequestedByID")]
        public int? RequestedById { get; set; }
        /// <summary>
        /// the ID of the financial year
        /// </summary>
        [Column("FinancialYrID")]
        public int? FinancialYrId { get; set; }
        /// <summary>
        /// the ID of the company..(usually the company in which system is installed)
        /// </summary>
        [Column("CompanyID")]
        public int? CompanyId { get; set; }
        /// <summary>
        /// the department initiating the requisition
        /// </summary>
        [Column("DepartmentID")]
        public int? DepartmentId { get; set; }
        /// <summary>
        /// the type of requisition (i.e. Purchase, Rent or Service)
        /// </summary>
        [Column("RequisitionTypeID")]
        public int? RequisitionTypeId { get; set; }
        /// <summary>
        /// the location of the company
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string Location { get; set; }
        /// <summary>
        /// the currency in which requisition is being quoted
        /// </summary>
        [Column("CurrencyID")]
        public int? CurrencyId { get; set; }
        /// <summary>
        /// the ID depicting the priority level for this requisition
        /// </summary>
        [Column("PriorityID")]
        public int? PriorityId { get; set; }
        /// <summary>
        /// the estimated total of the Requisition
        /// </summary>
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? RequisitionTotal { get; set; }
        /// <summary>
        /// the general purpose of the requisition
        /// </summary>
        [StringLength(100)]
        [Unicode(false)]
        public string RequisitionDescription { get; set; }
        [Column("RequisitionStatusID")]
        public int? RequisitionStatusId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string AuthorizedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime? AuthorizedDate { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LastUpdatedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime? LastUpdatedDate { get; set; }
    }
}