// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DigiProc.Models.Domain
{
    [Table("Vendor")]
    public partial class Vendor
    {
        [Key]
        [Column("VendorID")]
        public int VendorId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string VendorName { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string ContactPerson { get; set; }
        [Column("VendorTypeID")]
        public int? VendorTypeId { get; set; }
        /// <summary>
        /// the company registration number of the vendor
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string CompanyRegistrationNo { get; set; }
        [Column(TypeName = "date")]
        public DateTime? IncorporationDate { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string NameOfOwner { get; set; }
        /// <summary>
        /// the contact of the company
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string CompanyContact { get; set; }
        /// <summary>
        /// the website or social media presence of the company/vendor
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string CompanyWebsite { get; set; }
        /// <summary>
        /// the email address of the company
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string CompanyEmailAddress { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime? CreatedDate { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LastUpdatedBy { get; set; }
        [Column(TypeName = "date")]
        public DateTime? LastUpdatedDate { get; set; }
    }
}